set -euo pipefail

# shellcheck source=scripts/lib/ghcr-retry.sh
source "$GITHUB_WORKSPACE/scripts/lib/ghcr-retry.sh"

services=(proxy dns watchdog dhcp dhcp-proxy ui build-tools)
short_sha="${COMMIT_SHA::7}"
source_tag="sha-${short_sha}"
expected_prerelease=false
if [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
  expected_prerelease=true
  echo "::notice::Tag $TAG_NAME is a release candidate and will be published as a prerelease."
elif [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  expected_prerelease=false
else
  echo "::error::Unsupported release tag '$TAG_NAME'. Use vX.Y.Z or vX.Y.Z-rc.N."
  exit 1
fi

digest_for_image() {
  local image=$1
  local digest

  digest="$(ghcr_retry ghcr.io "$GHCR_RETRY_USERNAME" "$GHCR_RETRY_PASSWORD" -- docker buildx imagetools inspect "$image" --format '{{json .Manifest.Digest}}')"
  digest="${digest%\"}"
  digest="${digest#\"}"
  if [[ -z "$digest" || "$digest" = "null" ]]; then
    echo "::error::Could not read digest for $image."
    exit 1
  fi
  printf '%s\n' "$digest"
}

build_tools_image="ghcr.io/${REPOSITORY}/build-tools:${TAG_NAME}"
stack_pointer_image="ghcr.io/${REPOSITORY}/stack:${TAG_NAME}"
ghcr_retry ghcr.io "$GHCR_RETRY_USERNAME" "$GHCR_RETRY_PASSWORD" -- docker buildx imagetools inspect "$build_tools_image" >/dev/null
ghcr_retry ghcr.io "$GHCR_RETRY_USERNAME" "$GHCR_RETRY_PASSWORD" -- docker buildx imagetools inspect "$stack_pointer_image" >/dev/null
ghcr_retry ghcr.io "$GHCR_RETRY_USERNAME" "$GHCR_RETRY_PASSWORD" -- docker pull "$build_tools_image" >/dev/null
rust_base_digest="$(docker image inspect "$build_tools_image" --format '{{ index .Config.Labels "org.opencontainers.image.base.rust.digest" }}')"
golang_base_digest="$(docker image inspect "$build_tools_image" --format '{{ index .Config.Labels "org.opencontainers.image.base.golang.digest" }}')"
if [[ ! "$rust_base_digest" =~ ^sha256:[0-9a-f]{64}$ || ! "$golang_base_digest" =~ ^sha256:[0-9a-f]{64}$ ]]; then
  echo "::error::build-tools image is missing build-time base digest labels."
  exit 1
fi

image_notes_start='<!-- lancache-ng-image-tags:start -->'
image_notes_end='<!-- lancache-ng-image-tags:end -->'
notes_file="$(mktemp)"
{
  printf '%s\n' "$image_notes_start"
  printf 'This release source is the exact commit used by CI to build and publish the service images for %s.\n\n' "$TAG_NAME"
  printf 'Commit: %s\n\n' "$COMMIT_SHA"
  printf 'Published image tags and digests:\n\n'
  for service in "${services[@]}"; do
    tag_image="ghcr.io/${REPOSITORY}/${service}:${TAG_NAME}"
    sha_image="ghcr.io/${REPOSITORY}/${service}:${source_tag}"
    tag_digest="$(digest_for_image "$tag_image")"
    sha_digest="$(digest_for_image "$sha_image")"
    if [[ "$tag_digest" != "$sha_digest" ]]; then
      echo "::error::Release tag digest for $tag_image does not match $sha_image."
      exit 1
    fi
    printf -- '- %s -> %s\n' "$tag_image" "$tag_digest"
  done
  printf '\nMatching immutable SHA image tags:\n\n'
  for service in "${services[@]}"; do
    sha_image="ghcr.io/${REPOSITORY}/${service}:${source_tag}"
    sha_digest="$(digest_for_image "$sha_image")"
    printf -- '- %s -> %s\n' "$sha_image" "$sha_digest"
  done
  printf '\nStack channel pointer:\n\n'
  printf -- '- %s -> %s\n' "$stack_pointer_image" "$(digest_for_image "$stack_pointer_image")"
  printf -- '- ghcr.io/%s/stack:%s -> %s\n' "$REPOSITORY" "$source_tag" "$(digest_for_image "ghcr.io/${REPOSITORY}/stack:${source_tag}")"
  printf '\nResolved build-tools base image digests:\n\n'
  printf -- '- rust:latest -> %s\n' "$rust_base_digest"
  printf -- '- golang:latest -> %s\n' "$golang_base_digest"
  printf '\nProvenance and SBOM status:\n\n'
  printf -- '- Provenance attestations are pushed to GHCR for every first-party service image digest and the stack channel-pointer digest.\n'
  printf -- '- SBOM artifacts are not generated by this workflow yet; release notes must not claim SBOM coverage until an SBOM-producing job is added.\n'
  printf '%s\n' "$image_notes_end"
} > "$notes_file"

docker run --rm \
  -e GITHUB_TOKEN \
  -e REPOSITORY \
  -e TAG_NAME \
  -e COMMIT_SHA \
  -e EXPECTED_PRERELEASE="$expected_prerelease" \
  -v "$notes_file:/tmp/lancache-release-notes.md:ro" \
  "$build_tools_image" \
  bash -s <<'UPDATE_RELEASE'
set -euo pipefail

api_url="https://api.github.com/repos/${REPOSITORY}"
auth_header="Authorization: Bearer ${GITHUB_TOKEN}"
accept_header="Accept: application/vnd.github+json"
version_header="X-GitHub-Api-Version: 2022-11-28"
image_notes_start='<!-- lancache-ng-image-tags:start -->'
image_notes_end='<!-- lancache-ng-image-tags:end -->'
expected_prerelease="$EXPECTED_PRERELEASE"

response_file="$(mktemp)"
status="$(curl -sS -o "$response_file" -w '%{http_code}' \
  -H "$auth_header" \
  -H "$accept_header" \
  -H "$version_header" \
  "$api_url/releases/tags/$TAG_NAME")"

if [ "$status" = "200" ]; then
  release_id="$(jq -r '.id' "$response_file")"
  existing_prerelease="$(jq -r '.prerelease' "$response_file")"
  if [ "$existing_prerelease" != "$expected_prerelease" ]; then
    echo "Existing GitHub release prerelease state does not match tag policy for $TAG_NAME." >&2
    echo "Expected prerelease=$expected_prerelease, found prerelease=$existing_prerelease." >&2
    exit 1
  fi
  existing_body="$(jq -r '.body // ""' "$response_file")"
  # shellcheck disable=SC2016
  updated_body="$(jq -nr \
    --arg body "$existing_body" \
    --arg notes "$(cat /tmp/lancache-release-notes.md)" \
    --arg start "$image_notes_start" \
    --arg end "$image_notes_end" \
    '
    if ($body | contains($start)) and ($body | contains($end)) then
      ($body | split($start)[0]) as $prefix
      | ($body | split($end)[1:] | join($end)) as $suffix
      | $prefix + $notes + $suffix
    elif ($body | length) > 0 then
      $body + "\n\n" + $notes
    else
      $notes
    end
    ')"
  jq -n \
    --arg body "$updated_body" \
    '{body:$body}' \
    > "$response_file.patch"
  curl -fsS -X PATCH \
    -H "$auth_header" \
    -H "$accept_header" \
    -H "$version_header" \
    -d @"$response_file.patch" \
    "$api_url/releases/$release_id" >/dev/null
elif [ "$status" = "404" ]; then
  # shellcheck disable=SC2016
  jq -n \
    --arg tag_name "$TAG_NAME" \
    --arg target_commitish "$COMMIT_SHA" \
    --arg name "$TAG_NAME" \
    --arg body "$(cat /tmp/lancache-release-notes.md)" \
    --argjson prerelease "$expected_prerelease" \
    '{tag_name:$tag_name, target_commitish:$target_commitish, name:$name, body:$body, draft:false, prerelease:$prerelease}' \
    > "$response_file.create"
  curl -fsS -X POST \
    -H "$auth_header" \
    -H "$accept_header" \
    -H "$version_header" \
    -d @"$response_file.create" \
    "$api_url/releases" >/dev/null
else
  cat "$response_file"
  echo "Failed to inspect GitHub release for $TAG_NAME; HTTP status $status" >&2
  exit 1
fi
UPDATE_RELEASE
