[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     warn
    storage.path  /data/flb-storage

[INPUT]
    Name          tail
    Path          /var/log/nginx/standard/access.log
    Tag           nginx.standard
    DB            /data/flb-standard.db
    Skip_Long_Lines On

[INPUT]
    Name          tail
    Path          /var/log/nginx/ssl/access.log
    Tag           nginx.ssl
    DB            /data/flb-ssl.db
    Skip_Long_Lines On

[OUTPUT]
    Name          file
    Match         nginx.standard
    Path          /var/log/lancache
    File          nginx-standard.log
    Format        plain

[OUTPUT]
    Name          file
    Match         nginx.ssl
    Path          /var/log/lancache
    File          nginx-ssl.log
    Format        plain
