#!/bin/bash
set -euo pipefail

DOMAINS_FILE="/etc/nginx/cdn-domains.txt"
HOST_ALLOWLIST_FILE="/etc/nginx/conf.d/00-host-allowlist.conf"
STREAM_TARGET_FILE="/etc/nginx/stream.d/00-stream-target.conf"
PROXY_SECURITY_MODE="${PROXY_SECURITY_MODE:-strict}"

mkdir -p /etc/nginx/stream.d

write_host_allowlist() {
    {
        echo "# Auto-generated by entrypoint — do not edit"
        echo "map \$host \$proxy_host_blocked {"
        if [ "$PROXY_SECURITY_MODE" = "lazy" ]; then
            echo "    default 0;"
        else
            echo "    default 1;"
            while IFS= read -r domain || [ -n "$domain" ]; do
                [[ -z "$domain" || "$domain" == \#* ]] && continue
                printf "    %-45s 0;\n" ".$domain"
            done < "$DOMAINS_FILE"
        fi
        echo "}"
    } > "$HOST_ALLOWLIST_FILE"
}

write_stream_target_map() {
    {
        echo "# Auto-generated by entrypoint — do not edit"
        echo "map \$ssl_preread_server_name \$stream_upstream {"
        if [ "$PROXY_SECURITY_MODE" = "lazy" ]; then
            echo "    default \$ssl_preread_server_name:443;"
        else
            echo "    default 127.0.0.1:9;"
            while IFS= read -r domain || [ -n "$domain" ]; do
                [[ -z "$domain" || "$domain" == \#* ]] && continue
                domain_escaped="$(printf '%s' "$domain" | sed 's/[.[\*^$()+?{}|]/\\&/g')"
                printf '    ~^((?:.+\\.)?%s)$ $1:443;\n' "$domain_escaped"
            done < "$DOMAINS_FILE"
        fi
        echo "}"
    } > "$STREAM_TARGET_FILE"
}

write_host_allowlist
write_stream_target_map

envsubst '${CACHE_MEM_MB} ${CACHE_MAX_SIZE} ${CACHE_INACTIVE}' \
    < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

envsubst '${CACHE_SLICE_SIZE} ${CACHE_VALID_HIT} ${CACHE_VALID_ANY}' \
    < /etc/nginx/proxy-params.conf.template > /etc/nginx/proxy-params.conf

echo "[lancache-standard] Validating nginx config..."
nginx -t

echo "[lancache-standard] Starting nginx..."
exec nginx -g "daemon off;"
