#!/usr/bin/env bats
# lancache-ng (https://github.com/wiki-mod/lancache-ng)
#
# Regression tests for setup.sh's cmd_secondary() function, which generates
# a docker-compose.yml for secondary DNS nodes. Guards against issue #652,
# where the healthcheck block was missing from the generated heredoc and
# kept regressing on refactors, and against issue #946, where PR #876
# fixed the weak `rec_control ping` probe (#869) only in the checked-in
# reference file (deploy/secondary/docker-compose.yml) and not in this
# heredoc, inverting that file's own "Generated by setup.sh secondary --
# do not edit manually" header. A dedicated sync-guard test below (not just
# a literal-string assertion here) additionally fails if the heredoc body
# and the checked-in reference ever diverge again, regardless of which
# specific field drifts.

setup() {
    repo_root="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
}

# Extracts the heredoc body setup.sh's cmd_secondary() writes to
# ${secondary_dir}/docker-compose.yml, from the write_generated_runtime_file
# line (exclusive) through the closing bare "EOF" line (exclusive, via
# `exit` before it would be printed). Shared by both tests below so the
# extraction logic can't silently diverge between them the way it briefly
# did here -- this project's own #822 pattern (the same parsing logic
# hand-duplicated across call sites until one copy drifts) applies just as
# much to test helpers as it does to production code.
extract_cmd_secondary_heredoc() {
    local heredoc_start
    heredoc_start=$(grep -n 'write_generated_runtime_file "${secondary_dir}/docker-compose.yml" <<EOF' \
        "$repo_root/setup.sh" | cut -d: -f1)
    [[ -n "$heredoc_start" ]] || return 1

    awk -v start="$heredoc_start" '
        NR <= start { next }
        /^EOF$/ { exit }
        found || /^services:/ { found = 1; print }
    ' "$repo_root/setup.sh"
}

@test "cmd_secondary heredoc in setup.sh contains healthcheck block" {
    # Regression test for #652: the heredoc that generates the secondary
    # docker-compose.yml must include a healthcheck block. This block is
    # critical for PowerDNS health detection in production.

    local extracted_heredoc
    extracted_heredoc=$(extract_cmd_secondary_heredoc) \
        || skip "Could not find cmd_secondary heredoc start"

    # Verify the essential healthcheck fields are present in order
    echo "$extracted_heredoc" | grep -q "healthcheck:" \
        || fail "healthcheck: block missing"

    # Regression guard for #946: the heredoc must emit the real dig-based
    # query/response probe (AG-VAL-018), not the old rec_control-ping-only
    # check (AG-VAL-019 -- proves control-socket liveness, not that DNS
    # actually resolves). Assert both the presence of the new probe and the
    # explicit absence of the old one, so a partial revert (e.g. someone
    # merging an older heredoc back in) fails loudly.
    echo "$extracted_heredoc" | grep -qF 'test: ["CMD-SHELL", "dig @127.0.0.1 content1.steampowered.com A +short +time=2 +tries=1 | grep -q ."]' \
        || fail "healthcheck test command missing or incorrect (expected dig-based query/response probe)"

    if echo "$extracted_heredoc" | grep -qF 'test: ["CMD", "rec_control", "ping"]'; then
        fail "healthcheck test command regressed to the old rec_control-ping-only probe (#946)"
    fi

    echo "$extracted_heredoc" | grep -q "interval: 30s" \
        || fail "healthcheck interval missing"

    echo "$extracted_heredoc" | grep -q "timeout: 5s" \
        || fail "healthcheck timeout missing"

    echo "$extracted_heredoc" | grep -q "retries: 3" \
        || fail "healthcheck retries missing"

    echo "$extracted_heredoc" | grep -q "start_period: 20s" \
        || fail "healthcheck start_period missing"

    # Verify the healthcheck block comes after the ports block and before restart
    # by checking line ordering in the extracted heredoc
    local ports_line healthcheck_line restart_line

    ports_line=$(echo "$extracted_heredoc" | grep -n "ports:" | head -1 | cut -d: -f1)
    healthcheck_line=$(echo "$extracted_heredoc" | grep -n "healthcheck:" | head -1 | cut -d: -f1)
    restart_line=$(echo "$extracted_heredoc" | grep -n "restart: always" | head -1 | cut -d: -f1)

    [[ -n "$ports_line" && -n "$healthcheck_line" && -n "$restart_line" ]] \
        || fail "Could not determine line order of ports/healthcheck/restart blocks"

    [[ "$ports_line" -lt "$healthcheck_line" ]] \
        || fail "healthcheck block must come after ports block"

    [[ "$healthcheck_line" -lt "$restart_line" ]] \
        || fail "healthcheck block must come before restart block"
}

@test "cmd_secondary gives an actionable message for the issue #866 HTTP 503 refusal" {
    # Issue #866: register_secondary now refuses (HTTP 503) when the primary
    # has neither NATS_BIND_IP nor NATS_ADVERTISE_URL configured, instead of
    # silently handing out an unreachable NATS URL. Before this fix,
    # cmd_secondary's only non-2xx handling was one generic
    # "verify the registration token, secondary name, and primary server
    # logs" message -- accurate for a bad token/name (4xx), but actively
    # misleading for this 503 case, which is a primary-side configuration
    # gap the operator can't fix by re-checking their own command-line
    # arguments. Guards against that specific, more helpful branch
    # regressing back into the generic one on a future refactor.
    grep -q 'http_status" = "503"' "$repo_root/setup.sh" \
        || fail "cmd_secondary no longer special-cases HTTP 503"

    grep -q 'NATS_BIND_IP.*NATS_ADVERTISE_URL' "$repo_root/setup.sh" \
        || fail "the 503 die message no longer names NATS_BIND_IP/NATS_ADVERTISE_URL as the fix"

    # Setting NATS_BIND_IP/NATS_ADVERTISE_URL and restarting only the `ui`
    # container is not sufficient: the `nats` service itself still needs
    # docker-compose.nats-secondary.yml included (and to be recreated with
    # it) to actually publish port 4222 on that address. Guards against the
    # message regressing to only mention restarting `ui`, which would leave
    # an operator who follows it literally with the same silent
    # never-syncs failure mode issue #866 reports, just one step later.
    grep -q 'nats-secondary\.yml' "$repo_root/setup.sh" \
        || fail "the 503 die message no longer tells the operator to recreate the nats service with the nats-secondary.yml override"
}

@test "cmd_secondary's 503 recreate example includes --env-file .env.local for the .env.local case" {
    # Codex review on PR #881: Docker Compose only auto-loads the project
    # directory's default .env, never .env.local, so an operator who set
    # NATS_BIND_IP/NATS_ADVERTISE_URL in .env.local and then copies a
    # recreate command missing --env-file .env.local would still leave
    # docker-compose.nats-secondary.yml's ${NATS_BIND_IP:?...} guard unset --
    # NATS never actually gets recreated with the override applied. Guards
    # against the example regressing back to a bare `docker compose -f ...`
    # command that silently assumes .env only.
    grep -q -- '--env-file \.env\.local' "$repo_root/setup.sh" \
        || fail "the 503 die message's recreate example no longer shows --env-file .env.local for the .env.local case"
}

@test "cmd_secondary heredoc body stays in sync with the checked-in deploy/secondary/docker-compose.yml reference" {
    # Sync-guard for #946: deploy/secondary/docker-compose.yml's own header
    # claims "Generated by setup.sh secondary -- do not edit manually," but
    # PR #876 proved that claim false in practice by hand-editing the
    # checked-in reference file's healthcheck instead of this heredoc,
    # leaving the two silently diverged until #946 was filed. Rather than
    # asserting one specific field (the healthcheck test above already does
    # that), this diffs the entire generated body -- everything from
    # `services:` onward, which is exactly what write_generated_runtime_file
    # writes byte-for-byte -- against the checked-in reference, so ANY future
    # divergence between the two copies (not just a healthcheck regression)
    # fails here.
    local heredoc_body reference_body

    heredoc_body=$(extract_cmd_secondary_heredoc) \
        || skip "Could not find cmd_secondary heredoc start"

    # The heredoc is unquoted (<<EOF), so setup.sh must backslash-escape
    # every literal `$` and backtick meant to survive into the generated
    # file (otherwise the shell would expand/execute them at generation
    # time). Undo that escaping here so the comparison is against the same
    # literal text the reference file already contains unescaped.
    heredoc_body=$(echo "$heredoc_body" | sed -e 's/\\\$/$/g' -e 's/\\`/`/g')

    reference_body=$(awk '/^services:/ { found = 1 } found { print }' \
        "$repo_root/deploy/secondary/docker-compose.yml")

    diff <(printf '%s\n' "$heredoc_body") <(printf '%s\n' "$reference_body")
}

@test "cmd_secondary's registration POST sends the token via stdin, not argv" {
    # Regression guard, same exposure class as kea_ctrl_post's Basic-Auth fix
    # (#955/#956): a literal `-d "{\"token\":\"${token}\", ...}"` argument
    # puts the registration token in this process's argv for the whole
    # request's lifetime (visible to anything reading `ps`/
    # `/proc/<pid>/cmdline` on this host). The body must instead be piped
    # into curl and read via `-d @-`, so the token never appears as a
    # command-line argument at all.
    grep -q 'curl -sS -o "\$response_file" -w "%{http_code}" -X POST \\' "$repo_root/setup.sh" \
        || fail "cmd_secondary's registration curl invocation not found where expected"

    grep -q -- '-d @-' "$repo_root/setup.sh" \
        || fail "registration POST no longer reads its body from stdin (-d @-) -- token may have regressed back into argv"

    if grep -qF '-d "{\"token\":\"${token}\"' "$repo_root/setup.sh"; then
        fail "registration token has regressed back into curl's argv via a literal -d \"...\" argument"
    fi
}

@test "cmd_secondary collects all missing required arguments and reports them together" {
    # Regression test to ensure that when multiple required arguments
    # (--primary, --token, --name, --proxy-ip) are missing, cmd_secondary
    # collects all of them and reports them in one error message, rather than
    # failing on the first missing argument and requiring the user to run
    # the command multiple times. This behavior matches the pattern used for
    # collecting missing fields from the primary server's response.

    # Verify the argument validation uses the missing_args array pattern
    grep -q 'missing_args=()' "$repo_root/setup.sh" \
        || fail "cmd_secondary no longer uses missing_args array pattern"

    # Verify all four required arguments are checked and added to the array
    grep -q 'missing_args+=(.*--primary' "$repo_root/setup.sh" \
        || fail "cmd_secondary does not collect missing --primary"

    grep -q 'missing_args+=(.*--token' "$repo_root/setup.sh" \
        || fail "cmd_secondary does not collect missing --token"

    grep -q 'missing_args+=(.*--name' "$repo_root/setup.sh" \
        || fail "cmd_secondary does not collect missing --name"

    grep -q 'missing_args+=(.*--proxy-ip' "$repo_root/setup.sh" \
        || fail "cmd_secondary does not collect missing --proxy-ip"

    # Verify that the error is reported with all missing arguments at once
    # (using ${missing_args[*]} pattern similar to missing_fields)
    grep -q 'die.*missing_args\[' "$repo_root/setup.sh" \
        || fail "cmd_secondary does not report all missing arguments together"
}
