#!/usr/bin/env bats
# lancache-ng (https://github.com/wiki-mod/lancache-ng)
#
# Regression tests for setup.sh's cmd_secondary() function, which generates
# a docker-compose.yml for secondary DNS nodes. Guards against issue #652,
# where the healthcheck block was missing from the generated heredoc and
# kept regressing on refactors, and against issue #946, where PR #876
# fixed the weak `rec_control ping` probe (#869) only in the checked-in
# reference file (deploy/secondary/docker-compose.yml) and not in this
# heredoc, inverting that file's own "Generated by setup.sh secondary --
# do not edit manually" header. A dedicated sync-guard test below (not just
# a literal-string assertion here) additionally fails if the heredoc body
# and the checked-in reference ever diverge again, regardless of which
# specific field drifts.

setup() {
    repo_root="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
}

@test "cmd_secondary heredoc in setup.sh contains healthcheck block" {
    # Regression test for #652: the heredoc that generates the secondary
    # docker-compose.yml must include a healthcheck block. This block is
    # critical for PowerDNS health detection in production.
    #
    # Extract the heredoc from setup.sh's cmd_secondary function (lines between
    # 'write_generated_runtime_file "${secondary_dir}/docker-compose.yml" <<EOF'
    # and the closing EOF), then verify it contains the healthcheck block with
    # all required fields in the correct YAML structure.

    local heredoc_start heredoc_end extracted_heredoc

    # Find the write_generated_runtime_file line that starts the docker-compose.yml heredoc
    heredoc_start=$(grep -n 'write_generated_runtime_file "${secondary_dir}/docker-compose.yml" <<EOF' \
        "$repo_root/setup.sh" | cut -d: -f1)

    [[ -n "$heredoc_start" ]] || skip "Could not find cmd_secondary heredoc start"

    # Extract lines from the start until the closing EOF on its own line
    # This is a simple regex-based extraction; sed is used to grab the range
    extracted_heredoc=$(sed -n "$((heredoc_start)),$((heredoc_start + 100))p" "$repo_root/setup.sh" \
        | sed '/^EOF$/q')

    # Verify the essential healthcheck fields are present in order
    echo "$extracted_heredoc" | grep -q "healthcheck:" \
        || fail "healthcheck: block missing"

    # Regression guard for #946: the heredoc must emit the real dig-based
    # query/response probe (AG-VAL-018), not the old rec_control-ping-only
    # check (AG-VAL-019 -- proves control-socket liveness, not that DNS
    # actually resolves). Assert both the presence of the new probe and the
    # explicit absence of the old one, so a partial revert (e.g. someone
    # merging an older heredoc back in) fails loudly.
    echo "$extracted_heredoc" | grep -qF 'test: ["CMD-SHELL", "dig @127.0.0.1 steamcontent.com A +short +time=2 +tries=1 | grep -q ."]' \
        || fail "healthcheck test command missing or incorrect (expected dig-based query/response probe)"

    if echo "$extracted_heredoc" | grep -qF 'test: ["CMD", "rec_control", "ping"]'; then
        fail "healthcheck test command regressed to the old rec_control-ping-only probe (#946)"
    fi

    echo "$extracted_heredoc" | grep -q "interval: 30s" \
        || fail "healthcheck interval missing"

    echo "$extracted_heredoc" | grep -q "timeout: 5s" \
        || fail "healthcheck timeout missing"

    echo "$extracted_heredoc" | grep -q "retries: 3" \
        || fail "healthcheck retries missing"

    echo "$extracted_heredoc" | grep -q "start_period: 20s" \
        || fail "healthcheck start_period missing"

    # Verify the healthcheck block comes after the ports block and before restart
    # by checking line ordering in the extracted heredoc
    local ports_line healthcheck_line restart_line

    ports_line=$(echo "$extracted_heredoc" | grep -n "ports:" | head -1 | cut -d: -f1)
    healthcheck_line=$(echo "$extracted_heredoc" | grep -n "healthcheck:" | head -1 | cut -d: -f1)
    restart_line=$(echo "$extracted_heredoc" | grep -n "restart: always" | head -1 | cut -d: -f1)

    [[ -n "$ports_line" && -n "$healthcheck_line" && -n "$restart_line" ]] \
        || fail "Could not determine line order of ports/healthcheck/restart blocks"

    [[ "$ports_line" -lt "$healthcheck_line" ]] \
        || fail "healthcheck block must come after ports block"

    [[ "$healthcheck_line" -lt "$restart_line" ]] \
        || fail "healthcheck block must come before restart block"
}

@test "cmd_secondary gives an actionable message for the issue #866 HTTP 503 refusal" {
    # Issue #866: register_secondary now refuses (HTTP 503) when the primary
    # has neither NATS_BIND_IP nor NATS_ADVERTISE_URL configured, instead of
    # silently handing out an unreachable NATS URL. Before this fix,
    # cmd_secondary's only non-2xx handling was one generic
    # "verify the registration token, secondary name, and primary server
    # logs" message -- accurate for a bad token/name (4xx), but actively
    # misleading for this 503 case, which is a primary-side configuration
    # gap the operator can't fix by re-checking their own command-line
    # arguments. Guards against that specific, more helpful branch
    # regressing back into the generic one on a future refactor.
    grep -q 'http_status" = "503"' "$repo_root/setup.sh" \
        || fail "cmd_secondary no longer special-cases HTTP 503"

    grep -q 'NATS_BIND_IP.*NATS_ADVERTISE_URL' "$repo_root/setup.sh" \
        || fail "the 503 die message no longer names NATS_BIND_IP/NATS_ADVERTISE_URL as the fix"

    # Setting NATS_BIND_IP/NATS_ADVERTISE_URL and restarting only the `ui`
    # container is not sufficient: the `nats` service itself still needs
    # docker-compose.nats-secondary.yml included (and to be recreated with
    # it) to actually publish port 4222 on that address. Guards against the
    # message regressing to only mention restarting `ui`, which would leave
    # an operator who follows it literally with the same silent
    # never-syncs failure mode issue #866 reports, just one step later.
    grep -q 'nats-secondary\.yml' "$repo_root/setup.sh" \
        || fail "the 503 die message no longer tells the operator to recreate the nats service with the nats-secondary.yml override"
}

@test "cmd_secondary's 503 recreate example includes --env-file .env.local for the .env.local case" {
    # Codex review on PR #881: Docker Compose only auto-loads the project
    # directory's default .env, never .env.local, so an operator who set
    # NATS_BIND_IP/NATS_ADVERTISE_URL in .env.local and then copies a
    # recreate command missing --env-file .env.local would still leave
    # docker-compose.nats-secondary.yml's ${NATS_BIND_IP:?...} guard unset --
    # NATS never actually gets recreated with the override applied. Guards
    # against the example regressing back to a bare `docker compose -f ...`
    # command that silently assumes .env only.
    grep -q -- '--env-file \.env\.local' "$repo_root/setup.sh" \
        || fail "the 503 die message's recreate example no longer shows --env-file .env.local for the .env.local case"
}

@test "cmd_secondary heredoc body stays in sync with the checked-in deploy/secondary/docker-compose.yml reference" {
    # Sync-guard for #946: deploy/secondary/docker-compose.yml's own header
    # claims "Generated by setup.sh secondary -- do not edit manually," but
    # PR #876 proved that claim false in practice by hand-editing the
    # checked-in reference file's healthcheck instead of this heredoc,
    # leaving the two silently diverged until #946 was filed. Rather than
    # asserting one specific field (the healthcheck test above already does
    # that), this diffs the entire generated body -- everything from
    # `services:` onward, which is exactly what write_generated_runtime_file
    # writes byte-for-byte -- against the checked-in reference, so ANY future
    # divergence between the two copies (not just a healthcheck regression)
    # fails here.
    local heredoc_start heredoc_body reference_body

    heredoc_start=$(grep -n 'write_generated_runtime_file "${secondary_dir}/docker-compose.yml" <<EOF' \
        "$repo_root/setup.sh" | cut -d: -f1)
    [[ -n "$heredoc_start" ]] || skip "Could not find cmd_secondary heredoc start"

    # The heredoc is unquoted (<<EOF), so setup.sh must backslash-escape
    # every literal `$` and backtick meant to survive into the generated
    # file (otherwise the shell would expand/execute them at generation
    # time). Undo that escaping here so the comparison is against the same
    # literal text the reference file already contains unescaped.
    heredoc_body=$(awk -v start="$heredoc_start" '
        NR <= start { next }
        /^EOF$/ { exit }
        found || /^services:/ { found = 1; print }
    ' "$repo_root/setup.sh" | sed -e 's/\\\$/$/g' -e 's/\\`/`/g')

    reference_body=$(awk '/^services:/ { found = 1 } found { print }' \
        "$repo_root/deploy/secondary/docker-compose.yml")

    diff <(printf '%s\n' "$heredoc_body") <(printf '%s\n' "$reference_body")
}
