#!/usr/bin/env bats
# lancache-ng (https://github.com/wiki-mod/lancache-ng)
#
# Regression tests for setup.sh's cmd_secondary() function, which generates
# a docker-compose.yml for secondary DNS nodes. Guards against issue #652,
# where the healthcheck block was missing from the generated heredoc and
# kept regressing on refactors, and against the direction-inversion found
# after #869: #869's fix replaced the weak `rec_control ping` healthcheck
# with a real dig-based query/response probe (AG-VAL-018) everywhere, but
# that PR hand-edited the checked-in reference file
# deploy/secondary/docker-compose.yml directly instead of updating this
# heredoc and regenerating -- inverting deploy/secondary/docker-compose.yml's
# own "Generated by setup.sh secondary -- do not edit manually" header. This
# left cmd_secondary() still emitting the old, weak healthcheck, and this
# very test file previously asserted that old string, actively locking the
# regression in place instead of catching it.

setup() {
    repo_root="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
}

# Extracts the heredoc body setup.sh's cmd_secondary() writes to
# ${secondary_dir}/docker-compose.yml, from the write_generated_runtime_file
# call through the closing EOF (exclusive on both ends: the
# write_generated_runtime_file line itself and the bare "EOF" delimiter line
# are dropped from the result). A generous +100 line window is used since
# the heredoc content itself is only ~50 lines; sed stops at the first bare
# "EOF" line regardless. `sed -n '/^EOF$/q'` still auto-prints the matching
# "EOF" line before quitting, so a trailing `grep -v '^EOF$'` removes it --
# without this, the sync-guard test below would see a spurious extra "EOF"
# line at the end that the reference file naturally doesn't have.
extract_cmd_secondary_heredoc() {
    local heredoc_start
    heredoc_start=$(grep -n 'write_generated_runtime_file "${secondary_dir}/docker-compose.yml" <<EOF' \
        "$repo_root/setup.sh" | cut -d: -f1)

    [[ -n "$heredoc_start" ]] || return 1

    sed -n "$((heredoc_start)),$((heredoc_start + 100))p" "$repo_root/setup.sh" \
        | sed '/^EOF$/q' \
        | grep -v '^EOF$'
}

@test "cmd_secondary heredoc in setup.sh contains healthcheck block" {
    # Regression test for #652: the heredoc that generates the secondary
    # docker-compose.yml must include a healthcheck block. This block is
    # critical for PowerDNS health detection in production.

    local extracted_heredoc
    extracted_heredoc=$(extract_cmd_secondary_heredoc) \
        || skip "Could not find cmd_secondary heredoc start"

    # Verify the essential healthcheck fields are present in order. The test
    # command itself is a real dig query/response probe (AG-VAL-018), not
    # bare `rec_control ping` (liveness only, AG-VAL-019) -- see #869.
    echo "$extracted_heredoc" | grep -q "healthcheck:" \
        || fail "healthcheck: block missing"

    echo "$extracted_heredoc" | grep -qF 'test: ["CMD-SHELL", "dig @127.0.0.1 steamcontent.com A +short +time=2 +tries=1 | grep -q ."]' \
        || fail "healthcheck test command missing or is not the real dig-based query/response probe (AG-VAL-018)"

    # Explicit regression guard: the old, weak liveness-only check must not
    # come back. Without this negative assertion, a future refactor could
    # satisfy the positive check above while leaving a stray old test line
    # elsewhere, or a partial revert could reintroduce it silently.
    echo "$extracted_heredoc" | grep -qF 'test: ["CMD", "rec_control", "ping"]' \
        && fail "healthcheck test command regressed back to the old rec_control-ping-only probe (AG-VAL-019 violation, see #869)"

    echo "$extracted_heredoc" | grep -q "interval: 30s" \
        || fail "healthcheck interval missing"

    echo "$extracted_heredoc" | grep -q "timeout: 5s" \
        || fail "healthcheck timeout missing"

    echo "$extracted_heredoc" | grep -q "retries: 3" \
        || fail "healthcheck retries missing"

    echo "$extracted_heredoc" | grep -q "start_period: 20s" \
        || fail "healthcheck start_period missing"

    # Verify the healthcheck block comes after the ports block and before restart
    # by checking line ordering in the extracted heredoc
    local ports_line healthcheck_line restart_line

    ports_line=$(echo "$extracted_heredoc" | grep -n "ports:" | head -1 | cut -d: -f1)
    healthcheck_line=$(echo "$extracted_heredoc" | grep -n "healthcheck:" | head -1 | cut -d: -f1)
    restart_line=$(echo "$extracted_heredoc" | grep -n "restart: always" | head -1 | cut -d: -f1)

    [[ -n "$ports_line" && -n "$healthcheck_line" && -n "$restart_line" ]] \
        || fail "Could not determine line order of ports/healthcheck/restart blocks"

    [[ "$ports_line" -lt "$healthcheck_line" ]] \
        || fail "healthcheck block must come after ports block"

    [[ "$healthcheck_line" -lt "$restart_line" ]] \
        || fail "healthcheck block must come before restart block"
}

@test "cmd_secondary heredoc stays in sync with the checked-in deploy/secondary/docker-compose.yml reference" {
    # Sync-guard for the direction-inversion class of bug found after #869:
    # deploy/secondary/docker-compose.yml is headed "Generated by setup.sh
    # secondary -- do not edit manually", i.e. cmd_secondary()'s heredoc is
    # the source of truth and the checked-in file should always be exactly
    # what that heredoc produces. #869 was fixed by hand-editing the
    # checked-in file instead, so the two silently diverged with no test
    # catching it. This test diffs the "services:" section of both, so any
    # future field added/changed on only one side fails loudly instead of
    # silently drifting again.
    #
    # The heredoc is unquoted (<<EOF) so it can interpolate a handful of
    # shell variables (name, existing secrets) at generation time; every
    # other "$" and "`" that must survive into the literal YAML output is
    # backslash-escaped in the heredoc source to prevent expansion/command
    # substitution. That escaping is the only expected difference from the
    # plain-text reference file, so it is undone here before diffing.
    local extracted_heredoc generated_body reference_body

    extracted_heredoc=$(extract_cmd_secondary_heredoc) \
        || skip "Could not find cmd_secondary heredoc start"

    generated_body=$(echo "$extracted_heredoc" | sed -n '/^services:/,$p')
    generated_body="${generated_body//\\\$/\$}"
    generated_body="${generated_body//\\\`/\`}"

    [[ -f "$repo_root/deploy/secondary/docker-compose.yml" ]] \
        || fail "deploy/secondary/docker-compose.yml reference file not found"

    reference_body=$(sed -n '/^services:/,$p' "$repo_root/deploy/secondary/docker-compose.yml")

    diff <(printf '%s\n' "$generated_body") <(printf '%s\n' "$reference_body") \
        || fail "cmd_secondary()'s heredoc in setup.sh has drifted from deploy/secondary/docker-compose.yml. The checked-in file must always match what the heredoc generates -- update setup.sh's heredoc (not the checked-in file) and keep both sides identical."
}

@test "cmd_secondary gives an actionable message for the issue #866 HTTP 503 refusal" {
    # Issue #866: register_secondary now refuses (HTTP 503) when the primary
    # has neither NATS_BIND_IP nor NATS_ADVERTISE_URL configured, instead of
    # silently handing out an unreachable NATS URL. Before this fix,
    # cmd_secondary's only non-2xx handling was one generic
    # "verify the registration token, secondary name, and primary server
    # logs" message -- accurate for a bad token/name (4xx), but actively
    # misleading for this 503 case, which is a primary-side configuration
    # gap the operator can't fix by re-checking their own command-line
    # arguments. Guards against that specific, more helpful branch
    # regressing back into the generic one on a future refactor.
    grep -q 'http_status" = "503"' "$repo_root/setup.sh" \
        || fail "cmd_secondary no longer special-cases HTTP 503"

    grep -q 'NATS_BIND_IP.*NATS_ADVERTISE_URL' "$repo_root/setup.sh" \
        || fail "the 503 die message no longer names NATS_BIND_IP/NATS_ADVERTISE_URL as the fix"

    # Setting NATS_BIND_IP/NATS_ADVERTISE_URL and restarting only the `ui`
    # container is not sufficient: the `nats` service itself still needs
    # docker-compose.nats-secondary.yml included (and to be recreated with
    # it) to actually publish port 4222 on that address. Guards against the
    # message regressing to only mention restarting `ui`, which would leave
    # an operator who follows it literally with the same silent
    # never-syncs failure mode issue #866 reports, just one step later.
    grep -q 'nats-secondary\.yml' "$repo_root/setup.sh" \
        || fail "the 503 die message no longer tells the operator to recreate the nats service with the nats-secondary.yml override"
}

@test "cmd_secondary's 503 recreate example includes --env-file .env.local for the .env.local case" {
    # Codex review on PR #881: Docker Compose only auto-loads the project
    # directory's default .env, never .env.local, so an operator who set
    # NATS_BIND_IP/NATS_ADVERTISE_URL in .env.local and then copies a
    # recreate command missing --env-file .env.local would still leave
    # docker-compose.nats-secondary.yml's ${NATS_BIND_IP:?...} guard unset --
    # NATS never actually gets recreated with the override applied. Guards
    # against the example regressing back to a bare `docker compose -f ...`
    # command that silently assumes .env only.
    grep -q -- '--env-file \.env\.local' "$repo_root/setup.sh" \
        || fail "the 503 die message's recreate example no longer shows --env-file .env.local for the .env.local case"
}
