#!/bin/bash
set -euo pipefail

CA_DIR="/etc/nginx/ssl/ca"
CERT_DIR="/etc/nginx/ssl/certs"
DOMAINS_FILE="/etc/nginx/cdn-ssl-domains.txt"
SSL_MAP_FILE="/etc/nginx/conf.d/00-ssl-map.conf"
SERIAL_FILE="/tmp/lancache-ca.srl"  # writable location (CA_DIR may be read-only in prod)

# ----------------------------------------------------------------
# 1. Generate CA if not present (dev auto-setup)
# ----------------------------------------------------------------
if [ ! -f "$CA_DIR/ca.crt" ] || [ ! -f "$CA_DIR/ca.key" ]; then
    echo "[lancache-ng] Generating CA certificate (first-time setup)..."
    mkdir -p "$CA_DIR"
    openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 \
        -subj "/CN=LanCache-NG CA/O=LanCache-NG/C=DE" \
        -keyout "$CA_DIR/ca.key" \
        -out    "$CA_DIR/ca.crt" 2>/dev/null
    echo ""
    echo "╔══════════════════════════════════════════════════════════════════╗"
    echo "║              ACTION REQUIRED — READ BEFORE CONTINUING            ║"
    echo "╠══════════════════════════════════════════════════════════════════╣"
    echo "║                                                                  ║"
    echo "║  A CA certificate has been generated and saved to:               ║"
    echo "║    certs/ca.crt  (in your lancache-ng directory)                 ║"
    echo "║                                                                  ║"
    echo "║  Every client that uses the SSL mode MUST install this           ║"
    echo "║  certificate once. Without it, browsers will show a             ║"
    echo "║  security warning and downloads will fail.                       ║"
    echo "║                                                                  ║"
    echo "║  Instructions per OS: docs/install-ca-cert.md                   ║"
    echo "║                                                                  ║"
    echo "║  This message only appears once. The cert will be reused         ║"
    echo "║  on every subsequent start automatically.                        ║"
    echo "╚══════════════════════════════════════════════════════════════════╝"
    echo ""
fi

# Serial counter for cert signing (must be in /tmp, not CA_DIR which may be read-only)
echo "01" > "$SERIAL_FILE"

# ----------------------------------------------------------------
# 2. Generate per-domain wildcard certs signed by our CA
# ----------------------------------------------------------------
mkdir -p "$CERT_DIR"

_sign_cert() {
    local cn="$1" key="$2" crt="$3" ext="${4:-}"
    openssl req -new -newkey rsa:2048 -nodes -subj "/CN=${cn}" \
        -keyout "$key" -out /tmp/lancache-cert.csr 2>/dev/null
    if [ -n "$ext" ]; then
        openssl x509 -req -days 3650 \
            -in /tmp/lancache-cert.csr \
            -CA "$CA_DIR/ca.crt" -CAkey "$CA_DIR/ca.key" -CAserial "$SERIAL_FILE" \
            -extfile <(printf "%s" "$ext") \
            -out "$crt" 2>/dev/null
    else
        openssl x509 -req -days 3650 \
            -in /tmp/lancache-cert.csr \
            -CA "$CA_DIR/ca.crt" -CAkey "$CA_DIR/ca.key" -CAserial "$SERIAL_FILE" \
            -out "$crt" 2>/dev/null
    fi
    rm -f /tmp/lancache-cert.csr
}

# Default fallback cert (no SAN — only used for unknown hostnames)
[ ! -f "$CERT_DIR/default.crt" ] && \
    _sign_cert "lancache-default" "$CERT_DIR/default.key" "$CERT_DIR/default.crt"

while IFS= read -r domain || [ -n "$domain" ]; do
    [[ -z "$domain" || "$domain" == \#* ]] && continue
    [ -f "$CERT_DIR/${domain}.crt" ] && continue

    echo "[lancache] Generating cert for $domain..."
    _sign_cert "$domain" \
        "$CERT_DIR/${domain}.key" \
        "$CERT_DIR/${domain}.crt" \
        "subjectAltName=DNS:${domain},DNS:*.${domain}"
done < "$DOMAINS_FILE"

# ----------------------------------------------------------------
# 3. Generate SNI → cert map for nginx
# ----------------------------------------------------------------
{
    echo "# Auto-generated by entrypoint — do not edit"
    echo "map \$ssl_server_name \$ssl_cert_name {"
    echo "    hostnames;"
    while IFS= read -r domain || [ -n "$domain" ]; do
        [[ -z "$domain" || "$domain" == \#* ]] && continue
        printf "    %-45s %s;\n" "$domain"   "$domain"
        printf "    %-45s %s;\n" ".$domain"  "$domain"
    done < "$DOMAINS_FILE"
    echo "    default default;"
    echo "}"
} > "$SSL_MAP_FILE"

# ----------------------------------------------------------------
# 4. Render nginx.conf from template (always fresh on each start)
# ----------------------------------------------------------------
envsubst '${CACHE_MEM_MB} ${CACHE_MAX_SIZE}' \
    < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

# ----------------------------------------------------------------
# 5. Validate config and start nginx
# ----------------------------------------------------------------
echo "[lancache] Validating nginx config..."
nginx -t

echo "[lancache] Starting nginx..."
exec nginx -g "daemon off;"
