#!/bin/bash
set -euo pipefail

# setup-secondary.sh
# Register and launch a secondary DNS node with the primary lancache server.
#
# Usage: ./setup-secondary.sh --primary <url> --token <token> --name <name> --proxy-ip <ip>
#
# Example:
#   ./setup-secondary.sh --primary http://192.168.1.5:9090 \
#     --token MySecondaryToken123 \
#     --name secondary-office \
#     --proxy-ip 192.168.1.5

usage() {
  cat <<EOF_USAGE
Usage: $0 --primary <url> --token <token> --name <name> --proxy-ip <ip>

Required arguments:
  --primary <url>    Primary lancache UI/API URL, for example http://192.168.1.5:9090
  --token <token>    Secondary registration token from the primary server
  --name <name>      Secondary node name, using letters, numbers, and dashes only
  --proxy-ip <ip>    Primary proxy IP address clients should use for cached traffic

Example:
  $0 --primary http://192.168.1.5:9090 --token MyToken --name secondary-office --proxy-ip 192.168.1.5
EOF_USAGE
}

fail() {
  echo "Error: $*" >&2
  exit 1
}

require_value() {
  local option="$1"
  local value="${2:-}"

  if [[ -z "$value" || "$value" == --* ]]; then
    fail "${option} requires a value"
  fi
}

# Argument parsing
primary=""
token=""
name=""
proxy_ip=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --primary)
      require_value "$1" "${2:-}"
      primary="$2"
      shift 2
      ;;
    --token)
      require_value "$1" "${2:-}"
      token="$2"
      shift 2
      ;;
    --name)
      require_value "$1" "${2:-}"
      name="$2"
      shift 2
      ;;
    --proxy-ip)
      require_value "$1" "${2:-}"
      proxy_ip="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      fail "Unknown argument: $1"
      ;;
  esac
done

# Validate arguments
missing_args=()
[[ -n "$primary" ]] || missing_args+=("--primary")
[[ -n "$token" ]] || missing_args+=("--token")
[[ -n "$name" ]] || missing_args+=("--name")
[[ -n "$proxy_ip" ]] || missing_args+=("--proxy-ip")

if [[ ${#missing_args[@]} -gt 0 ]]; then
  usage >&2
  fail "Missing required argument(s): ${missing_args[*]}"
fi

# Check required tools
for cmd in curl docker; do
  if ! command -v "$cmd" &> /dev/null; then
    fail "$cmd is not installed or is not in PATH"
  fi
done

if ! docker compose version &> /dev/null; then
  fail "'docker compose' is not available; install Docker Compose v2 before continuing"
fi

# Validate name (alphanumeric + dash only)
if ! [[ "$name" =~ ^[a-zA-Z0-9-]+$ ]]; then
  fail "--name must contain only alphanumeric characters and dashes"
fi

# POST to primary server
echo "Registering secondary '${name}' with primary server..."
response_file=$(mktemp)
trap 'rm -f "$response_file"' EXIT

http_status=""
if ! http_status=$(curl -sS -o "$response_file" -w "%{http_code}" -X POST \
  -H "Content-Type: application/json" \
  -d "{\"token\":\"${token}\",\"name\":\"${name}\"}" \
  "${primary}/api/secondary/register"); then
  fail "Failed to connect to primary server at ${primary}. Check the URL, network connectivity, and that the primary service is running."
fi

response=$(cat "$response_file")

if [[ ! "$http_status" =~ ^2 ]]; then
  fail "Primary server rejected the registration request with HTTP ${http_status}. Verify the registration token, secondary name, and primary server logs."
fi

# Validate response is not empty
if [[ -z "$response" ]]; then
  fail "Empty response from primary server after successful HTTP ${http_status} registration request"
fi

# Extract fields from JSON response using grep
# Expected fields: nats_url, nats_token, consumer_name, proxy_ip, pdns_api_key
nats_url=$(echo "$response" | grep -oP '"nats_url"\s*:\s*"\K[^"]*' || true)
nats_token=$(echo "$response" | grep -oP '"nats_token"\s*:\s*"\K[^"]*' || true)
consumer_name=$(echo "$response" | grep -oP '"consumer_name"\s*:\s*"\K[^"]*' || true)
pdns_api_key=$(echo "$response" | grep -oP '"pdns_api_key"\s*:\s*"\K[^"]*' || true)

# Validate we got all required fields
missing_fields=()
[[ -n "$nats_url" ]] || missing_fields+=("nats_url")
[[ -n "$nats_token" ]] || missing_fields+=("nats_token")
[[ -n "$consumer_name" ]] || missing_fields+=("consumer_name")
[[ -n "$pdns_api_key" ]] || missing_fields+=("pdns_api_key")

if [[ ${#missing_fields[@]} -gt 0 ]]; then
  fail "Invalid response from primary server; missing field(s): ${missing_fields[*]}"
fi

# Create secondary directory
secondary_dir="${name}"
if [[ -d "$secondary_dir" ]]; then
  fail "Directory '${secondary_dir}' already exists; choose a different --name or remove the existing directory"
fi

mkdir -p "$secondary_dir"

# Write docker-compose.yml
cat > "${secondary_dir}/docker-compose.yml" << 'EOF_COMPOSE'
# Secondary DNS node — run on a remote host.
# Generated by scripts/setup-secondary.sh — do not edit manually.
# To update tokens, re-run setup-secondary.sh with --rotate.

services:
  dns-secondary:
    image: ghcr.io/wiki-mod/lancache-ng/dns:latest
    environment:
      - PROXY_IP=${PROXY_IP}
      - PDNS_API_KEY=${PDNS_API_KEY}
      - NATS_URL=${NATS_URL}
      - NATS_TOKEN=${NATS_TOKEN}
      - NATS_CONSUMER=${NATS_CONSUMER}
      - DDNS_ALLOW_FROM=127.0.0.1
    volumes:
      - pdns-data:/var/lib/powerdns
    ports:
      - "${LISTEN_IP:-0.0.0.0}:53:53/udp"
      - "${LISTEN_IP:-0.0.0.0}:53:53/tcp"
    healthcheck:
      test: ["CMD", "rec_control", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  pdns-data:
EOF_COMPOSE

# Write .env file
cat > "${secondary_dir}/.env" << EOF_ENV
PROXY_IP=${proxy_ip}
PDNS_API_KEY=${pdns_api_key}
NATS_URL=${nats_url}
NATS_TOKEN=${nats_token}
NATS_CONSUMER=${consumer_name}
EOF_ENV

# Start containers
echo "Starting secondary DNS container..."
if ! (cd "$secondary_dir" && docker compose up -d); then
  fail "Failed to start docker compose in ${secondary_dir}. Review Docker logs and the generated compose file."
fi

# Success message
echo "Secondary DNS '${name}' is running. Configure this host's IP as DNS on your clients."
