#!/bin/bash
set -euo pipefail

# setup-secondary.sh
# Register and launch a secondary DNS node with the primary lancache server.
#
# Usage: ./setup-secondary.sh --primary <url> --token <token> --name <name> --proxy-ip <ip>
#
# Example:
#   ./setup-secondary.sh --primary http://192.168.1.5:9090 \
#     --token MySecondaryToken123 \
#     --name secondary-office \
#     --proxy-ip 192.168.1.5

# Argument parsing
primary=""
token=""
name=""
proxy_ip=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --primary)
      primary="$2"
      shift 2
      ;;
    --token)
      token="$2"
      shift 2
      ;;
    --name)
      name="$2"
      shift 2
      ;;
    --proxy-ip)
      proxy_ip="$2"
      shift 2
      ;;
    *)
      echo "Usage: $0 --primary <url> --token <token> --name <name> --proxy-ip <ip>"
      echo ""
      echo "Examples:"
      echo "  $0 --primary http://192.168.1.5:9090 --token MyToken --name secondary-office --proxy-ip 192.168.1.5"
      exit 1
      ;;
  esac
done

# Validate arguments
if [[ -z "$primary" || -z "$token" || -z "$name" || -z "$proxy_ip" ]]; then
  echo "Error: Missing required arguments"
  echo "Usage: $0 --primary <url> --token <token> --name <name> --proxy-ip <ip>"
  exit 1
fi

# Check required tools
for cmd in curl docker; do
  if ! command -v "$cmd" &> /dev/null; then
    echo "Error: $cmd is not installed"
    exit 1
  fi
done

if ! docker compose version &> /dev/null; then
  echo "Error: 'docker compose' is not available"
  exit 1
fi

# Validate name (alphanumeric + dash only)
if ! [[ "$name" =~ ^[a-zA-Z0-9-]+$ ]]; then
  echo "Error: name must contain only alphanumeric characters and dashes"
  exit 1
fi

# POST to primary server
echo "Registering secondary '${name}' with primary server..."
response=$(curl -s -X POST \
  -H "Content-Type: application/json" \
  -d "{\"token\":\"${token}\",\"name\":\"${name}\"}" \
  "${primary}/api/secondary/register")
exit_code=$?

# Check curl exit code
if [[ $exit_code -ne 0 ]]; then
  echo "Error: Failed to connect to primary server at ${primary}"
  exit 1
fi

# Validate response is not empty
if [[ -z "$response" ]]; then
  echo "Error: Empty response from primary server"
  exit 1
fi

# Extract fields from JSON response using grep
# Expected fields: nats_url, nats_token, consumer_name, proxy_ip, pdns_api_key
nats_url=$(echo "$response" | grep -oP '"nats_url"\s*:\s*"\K[^"]*' || true)
nats_token=$(echo "$response" | grep -oP '"nats_token"\s*:\s*"\K[^"]*' || true)
consumer_name=$(echo "$response" | grep -oP '"consumer_name"\s*:\s*"\K[^"]*' || true)
pdns_api_key=$(echo "$response" | grep -oP '"pdns_api_key"\s*:\s*"\K[^"]*' || true)

# Validate we got all required fields
if [[ -z "$nats_url" || -z "$nats_token" || -z "$consumer_name" || -z "$pdns_api_key" ]]; then
  echo "Error: Invalid response from primary server"
  echo "Response: $response"
  exit 1
fi

# Create secondary directory
secondary_dir="${name}"
if [[ -d "$secondary_dir" ]]; then
  echo "Error: Directory '${secondary_dir}' already exists"
  exit 1
fi

mkdir -p "$secondary_dir"

# Write docker-compose.yml
cat > "${secondary_dir}/docker-compose.yml" << 'EOF'
# Secondary DNS node — run on a remote host.
# Generated by scripts/setup-secondary.sh — do not edit manually.
# To update tokens, re-run setup-secondary.sh with --rotate.

services:
  dns-secondary:
    image: ghcr.io/wiki-mod/lancache-ng/dns:latest
    environment:
      - PROXY_IP=${PROXY_IP}
      - PDNS_API_KEY=${PDNS_API_KEY}
      - NATS_URL=${NATS_URL}
      - NATS_TOKEN=${NATS_TOKEN}
      - NATS_CONSUMER=${NATS_CONSUMER}
      - DDNS_ALLOW_FROM=127.0.0.1
    volumes:
      - pdns-data:/var/lib/powerdns
    ports:
      - "${LISTEN_IP:-0.0.0.0}:53:53/udp"
      - "${LISTEN_IP:-0.0.0.0}:53:53/tcp"
    healthcheck:
      test: ["CMD-SHELL", "rec_control ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  pdns-data:
EOF

# Write .env file
cat > "${secondary_dir}/.env" << EOF
PROXY_IP=${proxy_ip}
PDNS_API_KEY=${pdns_api_key}
NATS_URL=${nats_url}
NATS_TOKEN=${nats_token}
NATS_CONSUMER=${consumer_name}
EOF

# Start containers
echo "Starting secondary DNS container..."
cd "$secondary_dir"
docker compose up -d
exit_code=$?

if [[ $exit_code -ne 0 ]]; then
  echo "Error: Failed to start docker compose"
  cd ..
  exit 1
fi

cd ..

# Success message
echo "Secondary DNS '${name}' is running. Configure this host's IP as DNS on your clients."
