#!/usr/bin/env bash
# LanCache-NG (https://github.com/wiki-mod/lancache-ng)
# SPDX-License-Identifier: AGPL-3.0-or-later
# Render the full-setup compose override from immutable OCI digests. Digests
# already handed off by merge-manifests are consumed directly; only a service
# without a producer output (for example an untouched PR backfill) is resolved
# once from its event-unique staging tag and immediately pinned.
set -euo pipefail

output_file=${1:?output compose override path is required}
: "${REPOSITORY:?REPOSITORY is required}"
: "${IMAGE_TAG:?IMAGE_TAG is required}"

# shellcheck source=scripts/lib/ghcr-retry.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/ghcr-retry.sh"

resolve_digest() {
  local service=$1 supplied=$2 image digest
  if [[ "$supplied" =~ ^sha256:[0-9a-fA-F]{64}$ ]]; then
    printf '%s\n' "$supplied"
    return 0
  fi
  image="ghcr.io/${REPOSITORY}/${service}:${IMAGE_TAG}"
  echo "::notice::No producer digest was exported for $service; resolving $image once and pinning the result for this validation run." >&2
  digest="$(ghcr_retry ghcr.io "${GHCR_RETRY_USERNAME:-}" "${GHCR_RETRY_PASSWORD:-}" -- docker buildx imagetools inspect "$image" --format '{{json .Manifest.Digest}}')"
  digest="${digest%\"}"; digest="${digest#\"}"
  [[ "$digest" =~ ^sha256:[0-9a-fA-F]{64}$ ]] || { echo "::error::Could not resolve immutable digest for $image: '$digest'." >&2; exit 1; }
  printf '%s\n' "$digest"
}

proxy_digest="$(resolve_digest proxy "${PROXY_DIGEST:-}")"
dns_digest="$(resolve_digest dns "${DNS_DIGEST:-}")"
watchdog_digest="$(resolve_digest watchdog "${WATCHDOG_DIGEST:-}")"
ui_digest="$(resolve_digest ui "${UI_DIGEST:-}")"
build_tools_digest="$(resolve_digest build-tools "${BUILD_TOOLS_DIGEST:-}")"

mkdir -p "$(dirname "$output_file")"
cat > "$output_file" <<YAML
# Generated by scripts/render-full-setup-digest-override.sh for one CI run.
services:
  proxy:
    image: "ghcr.io/${REPOSITORY}/proxy@${proxy_digest}"
  dns-standard:
    image: "ghcr.io/${REPOSITORY}/dns@${dns_digest}"
  dns-ssl:
    image: "ghcr.io/${REPOSITORY}/dns@${dns_digest}"
  watchdog:
    image: "ghcr.io/${REPOSITORY}/watchdog@${watchdog_digest}"
  retention:
    image: "ghcr.io/${REPOSITORY}/watchdog@${watchdog_digest}"
  ui:
    image: "ghcr.io/${REPOSITORY}/ui@${ui_digest}"
YAML

printf 'ghcr.io/%s/build-tools@%s\n' "$REPOSITORY" "$build_tools_digest"
